/*
 * generated by Xtext 2.17.0
 */
package a2b.ide.contentassist.antlr;

import a2b.ide.contentassist.antlr.internal.InternalA2BParser;
import a2b.services.A2BGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class A2BParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(A2BGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, A2BGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
			builder.put(grammarAccess.getDBAccess().getAlternatives_1(), "rule__DB__Alternatives_1");
			builder.put(grammarAccess.getDWAccess().getAlternatives_1(), "rule__DW__Alternatives_1");
			builder.put(grammarAccess.getDDAccess().getAlternatives_1(), "rule__DD__Alternatives_1");
			builder.put(grammarAccess.getInstructionAccess().getGroup_9(), "rule__Instruction__Group_9__0");
			builder.put(grammarAccess.getInstructionAccess().getGroup_10(), "rule__Instruction__Group_10__0");
			builder.put(grammarAccess.getInstructionAccess().getGroup_11(), "rule__Instruction__Group_11__0");
			builder.put(grammarAccess.getDBAccess().getGroup(), "rule__DB__Group__0");
			builder.put(grammarAccess.getDWAccess().getGroup(), "rule__DW__Group__0");
			builder.put(grammarAccess.getDDAccess().getGroup(), "rule__DD__Group__0");
			builder.put(grammarAccess.getBase64Access().getGroup(), "rule__Base64__Group__0");
			builder.put(grammarAccess.getORGAccess().getGroup(), "rule__ORG__Group__0");
			builder.put(grammarAccess.getINCLUDEAccess().getGroup(), "rule__INCLUDE__Group__0");
			builder.put(grammarAccess.getMACAccess().getGroup(), "rule__MAC__Group__0");
			builder.put(grammarAccess.getIPAccess().getGroup(), "rule__IP__Group__0");
			builder.put(grammarAccess.getHXSAccess().getGroup(), "rule__HXS__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementAssignment(), "rule__Model__ElementAssignment");
			builder.put(grammarAccess.getDBAccess().getStringValueAssignment_1_0(), "rule__DB__StringValueAssignment_1_0");
			builder.put(grammarAccess.getDBAccess().getIntValueAssignment_1_1(), "rule__DB__IntValueAssignment_1_1");
			builder.put(grammarAccess.getDWAccess().getStringValueAssignment_1_0(), "rule__DW__StringValueAssignment_1_0");
			builder.put(grammarAccess.getDWAccess().getIntValueAssignment_1_1(), "rule__DW__IntValueAssignment_1_1");
			builder.put(grammarAccess.getDDAccess().getStringValueAssignment_1_0(), "rule__DD__StringValueAssignment_1_0");
			builder.put(grammarAccess.getDDAccess().getLongValueAssignment_1_1(), "rule__DD__LongValueAssignment_1_1");
			builder.put(grammarAccess.getBase64Access().getValueAssignment_1(), "rule__Base64__ValueAssignment_1");
			builder.put(grammarAccess.getORGAccess().getValueAssignment_1(), "rule__ORG__ValueAssignment_1");
			builder.put(grammarAccess.getINCLUDEAccess().getValueAssignment_1(), "rule__INCLUDE__ValueAssignment_1");
			builder.put(grammarAccess.getMACAccess().getValueAssignment_1(), "rule__MAC__ValueAssignment_1");
			builder.put(grammarAccess.getIPAccess().getValueAssignment_1(), "rule__IP__ValueAssignment_1");
			builder.put(grammarAccess.getHXSAccess().getValueAssignment_1(), "rule__HXS__ValueAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private A2BGrammarAccess grammarAccess;

	@Override
	protected InternalA2BParser createParser() {
		InternalA2BParser result = new InternalA2BParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public A2BGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(A2BGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
