/**
 * generated by Xtext 2.17.0
 */
package a2b.a2B;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see a2b.a2B.A2BPackage
 * @generated
 */
public interface A2BFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  A2BFactory eINSTANCE = a2b.a2B.impl.A2BFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instruction</em>'.
   * @generated
   */
  Instruction createInstruction();

  /**
   * Returns a new object of class '<em>DB</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DB</em>'.
   * @generated
   */
  DB createDB();

  /**
   * Returns a new object of class '<em>Base64</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Base64</em>'.
   * @generated
   */
  Base64 createBase64();

  /**
   * Returns a new object of class '<em>ORG</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ORG</em>'.
   * @generated
   */
  ORG createORG();

  /**
   * Returns a new object of class '<em>INCLUDE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>INCLUDE</em>'.
   * @generated
   */
  INCLUDE createINCLUDE();

  /**
   * Returns a new object of class '<em>MAC</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MAC</em>'.
   * @generated
   */
  MAC createMAC();

  /**
   * Returns a new object of class '<em>IP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IP</em>'.
   * @generated
   */
  IP createIP();

  /**
   * Returns a new object of class '<em>HXS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>HXS</em>'.
   * @generated
   */
  HXS createHXS();

  /**
   * Returns a new object of class '<em>BE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BE</em>'.
   * @generated
   */
  BE createBE();

  /**
   * Returns a new object of class '<em>LE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LE</em>'.
   * @generated
   */
  LE createLE();

  /**
   * Returns a new object of class '<em>PCAP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PCAP</em>'.
   * @generated
   */
  PCAP createPCAP();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  A2BPackage getA2BPackage();

} //A2BFactory
