/**
 * generated by Xtext 2.17.0
 */
package a2b.a2B;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see a2b.a2B.A2BFactory
 * @model kind="package"
 * @generated
 */
public interface A2BPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "a2B";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.A2B.a2b";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "a2B";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  A2BPackage eINSTANCE = a2b.a2B.impl.A2BPackageImpl.init();

  /**
   * The meta object id for the '{@link a2b.a2B.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.ModelImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.InstructionImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.DBImpl <em>DB</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.DBImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getDB()
   * @generated
   */
  int DB = 2;

  /**
   * The feature id for the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB__STRING_VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Int Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB__INT_VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>DB</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.DWImpl <em>DW</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.DWImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getDW()
   * @generated
   */
  int DW = 3;

  /**
   * The feature id for the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DW__STRING_VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Int Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DW__INT_VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DW__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>DW</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DW_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.DDImpl <em>DD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.DDImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getDD()
   * @generated
   */
  int DD = 4;

  /**
   * The feature id for the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DD__STRING_VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Long Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DD__LONG_VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DD__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>DD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DD_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.STRImpl <em>STR</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.STRImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getSTR()
   * @generated
   */
  int STR = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>STR</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.Base64DecodeImpl <em>Base64 Decode</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.Base64DecodeImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getBase64Decode()
   * @generated
   */
  int BASE64_DECODE = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE64_DECODE__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Base64 Decode</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE64_DECODE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.Base64EncodeImpl <em>Base64 Encode</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.Base64EncodeImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getBase64Encode()
   * @generated
   */
  int BASE64_ENCODE = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE64_ENCODE__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Base64 Encode</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE64_ENCODE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.PADImpl <em>PAD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.PADImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getPAD()
   * @generated
   */
  int PAD = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAD__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAD__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>PAD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAD_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.INCLUDEImpl <em>INCLUDE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.INCLUDEImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getINCLUDE()
   * @generated
   */
  int INCLUDE = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>INCLUDE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.MACImpl <em>MAC</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.MACImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getMAC()
   * @generated
   */
  int MAC = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAC__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAC__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>MAC</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAC_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.IPImpl <em>IP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.IPImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getIP()
   * @generated
   */
  int IP = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>IP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.PXLImpl <em>PXL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.PXLImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getPXL()
   * @generated
   */
  int PXL = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PXL__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>PXL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PXL_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.HXSImpl <em>HXS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.HXSImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getHXS()
   * @generated
   */
  int HXS = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HXS__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HXS__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>HXS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HXS_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.CRC16Impl <em>CRC16</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.CRC16Impl
   * @see a2b.a2B.impl.A2BPackageImpl#getCRC16()
   * @generated
   */
  int CRC16 = 14;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRC16__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>CRC16</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRC16_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.CRC32Impl <em>CRC32</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.CRC32Impl
   * @see a2b.a2B.impl.A2BPackageImpl#getCRC32()
   * @generated
   */
  int CRC32 = 15;

  /**
   * The feature id for the '<em><b>Crc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRC32__CRC_VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>CRC32</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRC32_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.BEImpl <em>BE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.BEImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getBE()
   * @generated
   */
  int BE = 16;

  /**
   * The number of structural features of the '<em>BE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.LEImpl <em>LE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.LEImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getLE()
   * @generated
   */
  int LE = 17;

  /**
   * The number of structural features of the '<em>LE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.PCAPImpl <em>PCAP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.PCAPImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getPCAP()
   * @generated
   */
  int PCAP = 18;

  /**
   * The number of structural features of the '<em>PCAP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PCAP_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.NLImpl <em>NL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.NLImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getNL()
   * @generated
   */
  int NL = 19;

  /**
   * The number of structural features of the '<em>NL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NL_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link a2b.a2B.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see a2b.a2B.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link a2b.a2B.Model#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see a2b.a2B.Model#getElement()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Element();

  /**
   * Returns the meta object for class '{@link a2b.a2B.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see a2b.a2B.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link a2b.a2B.DB <em>DB</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DB</em>'.
   * @see a2b.a2B.DB
   * @generated
   */
  EClass getDB();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DB#getStringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String Value</em>'.
   * @see a2b.a2B.DB#getStringValue()
   * @see #getDB()
   * @generated
   */
  EAttribute getDB_StringValue();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DB#getIntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int Value</em>'.
   * @see a2b.a2B.DB#getIntValue()
   * @see #getDB()
   * @generated
   */
  EAttribute getDB_IntValue();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DB#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.DB#getCrcValue()
   * @see #getDB()
   * @generated
   */
  EAttribute getDB_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.DW <em>DW</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DW</em>'.
   * @see a2b.a2B.DW
   * @generated
   */
  EClass getDW();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DW#getStringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String Value</em>'.
   * @see a2b.a2B.DW#getStringValue()
   * @see #getDW()
   * @generated
   */
  EAttribute getDW_StringValue();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DW#getIntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int Value</em>'.
   * @see a2b.a2B.DW#getIntValue()
   * @see #getDW()
   * @generated
   */
  EAttribute getDW_IntValue();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DW#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.DW#getCrcValue()
   * @see #getDW()
   * @generated
   */
  EAttribute getDW_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.DD <em>DD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DD</em>'.
   * @see a2b.a2B.DD
   * @generated
   */
  EClass getDD();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DD#getStringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String Value</em>'.
   * @see a2b.a2B.DD#getStringValue()
   * @see #getDD()
   * @generated
   */
  EAttribute getDD_StringValue();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DD#getLongValue <em>Long Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Long Value</em>'.
   * @see a2b.a2B.DD#getLongValue()
   * @see #getDD()
   * @generated
   */
  EAttribute getDD_LongValue();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DD#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.DD#getCrcValue()
   * @see #getDD()
   * @generated
   */
  EAttribute getDD_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.STR <em>STR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>STR</em>'.
   * @see a2b.a2B.STR
   * @generated
   */
  EClass getSTR();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.STR#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.STR#getValue()
   * @see #getSTR()
   * @generated
   */
  EAttribute getSTR_Value();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.STR#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.STR#getCrcValue()
   * @see #getSTR()
   * @generated
   */
  EAttribute getSTR_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.Base64Decode <em>Base64 Decode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Base64 Decode</em>'.
   * @see a2b.a2B.Base64Decode
   * @generated
   */
  EClass getBase64Decode();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.Base64Decode#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.Base64Decode#getValue()
   * @see #getBase64Decode()
   * @generated
   */
  EAttribute getBase64Decode_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.Base64Encode <em>Base64 Encode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Base64 Encode</em>'.
   * @see a2b.a2B.Base64Encode
   * @generated
   */
  EClass getBase64Encode();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.Base64Encode#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.Base64Encode#getValue()
   * @see #getBase64Encode()
   * @generated
   */
  EAttribute getBase64Encode_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.PAD <em>PAD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PAD</em>'.
   * @see a2b.a2B.PAD
   * @generated
   */
  EClass getPAD();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.PAD#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.PAD#getValue()
   * @see #getPAD()
   * @generated
   */
  EAttribute getPAD_Value();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.PAD#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.PAD#getCrcValue()
   * @see #getPAD()
   * @generated
   */
  EAttribute getPAD_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.INCLUDE <em>INCLUDE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>INCLUDE</em>'.
   * @see a2b.a2B.INCLUDE
   * @generated
   */
  EClass getINCLUDE();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.INCLUDE#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.INCLUDE#getValue()
   * @see #getINCLUDE()
   * @generated
   */
  EAttribute getINCLUDE_Value();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.INCLUDE#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.INCLUDE#getCrcValue()
   * @see #getINCLUDE()
   * @generated
   */
  EAttribute getINCLUDE_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.MAC <em>MAC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MAC</em>'.
   * @see a2b.a2B.MAC
   * @generated
   */
  EClass getMAC();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.MAC#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.MAC#getValue()
   * @see #getMAC()
   * @generated
   */
  EAttribute getMAC_Value();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.MAC#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.MAC#getCrcValue()
   * @see #getMAC()
   * @generated
   */
  EAttribute getMAC_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.IP <em>IP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IP</em>'.
   * @see a2b.a2B.IP
   * @generated
   */
  EClass getIP();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.IP#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.IP#getValue()
   * @see #getIP()
   * @generated
   */
  EAttribute getIP_Value();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.IP#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.IP#getCrcValue()
   * @see #getIP()
   * @generated
   */
  EAttribute getIP_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.PXL <em>PXL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PXL</em>'.
   * @see a2b.a2B.PXL
   * @generated
   */
  EClass getPXL();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.PXL#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.PXL#getValue()
   * @see #getPXL()
   * @generated
   */
  EAttribute getPXL_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.HXS <em>HXS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>HXS</em>'.
   * @see a2b.a2B.HXS
   * @generated
   */
  EClass getHXS();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.HXS#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.HXS#getValue()
   * @see #getHXS()
   * @generated
   */
  EAttribute getHXS_Value();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.HXS#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.HXS#getCrcValue()
   * @see #getHXS()
   * @generated
   */
  EAttribute getHXS_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.CRC16 <em>CRC16</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CRC16</em>'.
   * @see a2b.a2B.CRC16
   * @generated
   */
  EClass getCRC16();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.CRC16#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.CRC16#getCrcValue()
   * @see #getCRC16()
   * @generated
   */
  EAttribute getCRC16_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.CRC32 <em>CRC32</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CRC32</em>'.
   * @see a2b.a2B.CRC32
   * @generated
   */
  EClass getCRC32();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.CRC32#getCrcValue <em>Crc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Crc Value</em>'.
   * @see a2b.a2B.CRC32#getCrcValue()
   * @see #getCRC32()
   * @generated
   */
  EAttribute getCRC32_CrcValue();

  /**
   * Returns the meta object for class '{@link a2b.a2B.BE <em>BE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BE</em>'.
   * @see a2b.a2B.BE
   * @generated
   */
  EClass getBE();

  /**
   * Returns the meta object for class '{@link a2b.a2B.LE <em>LE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LE</em>'.
   * @see a2b.a2B.LE
   * @generated
   */
  EClass getLE();

  /**
   * Returns the meta object for class '{@link a2b.a2B.PCAP <em>PCAP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PCAP</em>'.
   * @see a2b.a2B.PCAP
   * @generated
   */
  EClass getPCAP();

  /**
   * Returns the meta object for class '{@link a2b.a2B.NL <em>NL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>NL</em>'.
   * @see a2b.a2B.NL
   * @generated
   */
  EClass getNL();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  A2BFactory getA2BFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link a2b.a2B.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.ModelImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENT = eINSTANCE.getModel_Element();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.InstructionImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.DBImpl <em>DB</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.DBImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getDB()
     * @generated
     */
    EClass DB = eINSTANCE.getDB();

    /**
     * The meta object literal for the '<em><b>String Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DB__STRING_VALUE = eINSTANCE.getDB_StringValue();

    /**
     * The meta object literal for the '<em><b>Int Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DB__INT_VALUE = eINSTANCE.getDB_IntValue();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DB__CRC_VALUE = eINSTANCE.getDB_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.DWImpl <em>DW</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.DWImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getDW()
     * @generated
     */
    EClass DW = eINSTANCE.getDW();

    /**
     * The meta object literal for the '<em><b>String Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DW__STRING_VALUE = eINSTANCE.getDW_StringValue();

    /**
     * The meta object literal for the '<em><b>Int Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DW__INT_VALUE = eINSTANCE.getDW_IntValue();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DW__CRC_VALUE = eINSTANCE.getDW_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.DDImpl <em>DD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.DDImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getDD()
     * @generated
     */
    EClass DD = eINSTANCE.getDD();

    /**
     * The meta object literal for the '<em><b>String Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DD__STRING_VALUE = eINSTANCE.getDD_StringValue();

    /**
     * The meta object literal for the '<em><b>Long Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DD__LONG_VALUE = eINSTANCE.getDD_LongValue();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DD__CRC_VALUE = eINSTANCE.getDD_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.STRImpl <em>STR</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.STRImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getSTR()
     * @generated
     */
    EClass STR = eINSTANCE.getSTR();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STR__VALUE = eINSTANCE.getSTR_Value();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STR__CRC_VALUE = eINSTANCE.getSTR_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.Base64DecodeImpl <em>Base64 Decode</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.Base64DecodeImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getBase64Decode()
     * @generated
     */
    EClass BASE64_DECODE = eINSTANCE.getBase64Decode();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASE64_DECODE__VALUE = eINSTANCE.getBase64Decode_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.Base64EncodeImpl <em>Base64 Encode</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.Base64EncodeImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getBase64Encode()
     * @generated
     */
    EClass BASE64_ENCODE = eINSTANCE.getBase64Encode();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASE64_ENCODE__VALUE = eINSTANCE.getBase64Encode_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.PADImpl <em>PAD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.PADImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getPAD()
     * @generated
     */
    EClass PAD = eINSTANCE.getPAD();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAD__VALUE = eINSTANCE.getPAD_Value();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAD__CRC_VALUE = eINSTANCE.getPAD_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.INCLUDEImpl <em>INCLUDE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.INCLUDEImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getINCLUDE()
     * @generated
     */
    EClass INCLUDE = eINSTANCE.getINCLUDE();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INCLUDE__VALUE = eINSTANCE.getINCLUDE_Value();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INCLUDE__CRC_VALUE = eINSTANCE.getINCLUDE_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.MACImpl <em>MAC</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.MACImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getMAC()
     * @generated
     */
    EClass MAC = eINSTANCE.getMAC();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAC__VALUE = eINSTANCE.getMAC_Value();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAC__CRC_VALUE = eINSTANCE.getMAC_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.IPImpl <em>IP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.IPImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getIP()
     * @generated
     */
    EClass IP = eINSTANCE.getIP();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IP__VALUE = eINSTANCE.getIP_Value();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IP__CRC_VALUE = eINSTANCE.getIP_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.PXLImpl <em>PXL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.PXLImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getPXL()
     * @generated
     */
    EClass PXL = eINSTANCE.getPXL();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PXL__VALUE = eINSTANCE.getPXL_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.HXSImpl <em>HXS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.HXSImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getHXS()
     * @generated
     */
    EClass HXS = eINSTANCE.getHXS();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HXS__VALUE = eINSTANCE.getHXS_Value();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HXS__CRC_VALUE = eINSTANCE.getHXS_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.CRC16Impl <em>CRC16</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.CRC16Impl
     * @see a2b.a2B.impl.A2BPackageImpl#getCRC16()
     * @generated
     */
    EClass CRC16 = eINSTANCE.getCRC16();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CRC16__CRC_VALUE = eINSTANCE.getCRC16_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.CRC32Impl <em>CRC32</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.CRC32Impl
     * @see a2b.a2B.impl.A2BPackageImpl#getCRC32()
     * @generated
     */
    EClass CRC32 = eINSTANCE.getCRC32();

    /**
     * The meta object literal for the '<em><b>Crc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CRC32__CRC_VALUE = eINSTANCE.getCRC32_CrcValue();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.BEImpl <em>BE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.BEImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getBE()
     * @generated
     */
    EClass BE = eINSTANCE.getBE();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.LEImpl <em>LE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.LEImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getLE()
     * @generated
     */
    EClass LE = eINSTANCE.getLE();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.PCAPImpl <em>PCAP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.PCAPImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getPCAP()
     * @generated
     */
    EClass PCAP = eINSTANCE.getPCAP();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.NLImpl <em>NL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.NLImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getNL()
     * @generated
     */
    EClass NL = eINSTANCE.getNL();

  }

} //A2BPackage
