/**
 * generated by Xtext 2.17.0
 */
package a2b.a2B;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see a2b.a2B.A2BFactory
 * @model kind="package"
 * @generated
 */
public interface A2BPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "a2B";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.A2B.a2b";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "a2B";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  A2BPackage eINSTANCE = a2b.a2B.impl.A2BPackageImpl.init();

  /**
   * The meta object id for the '{@link a2b.a2B.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.ModelImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.InstructionImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.DBImpl <em>DB</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.DBImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getDB()
   * @generated
   */
  int DB = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>DB</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.Base64Impl <em>Base64</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.Base64Impl
   * @see a2b.a2B.impl.A2BPackageImpl#getBase64()
   * @generated
   */
  int BASE64 = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE64__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Base64</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE64_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.ORGImpl <em>ORG</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.ORGImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getORG()
   * @generated
   */
  int ORG = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORG__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>ORG</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORG_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.INCLUDEImpl <em>INCLUDE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.INCLUDEImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getINCLUDE()
   * @generated
   */
  int INCLUDE = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>INCLUDE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.MACImpl <em>MAC</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.MACImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getMAC()
   * @generated
   */
  int MAC = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAC__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>MAC</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAC_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.IPImpl <em>IP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.IPImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getIP()
   * @generated
   */
  int IP = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>IP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.HXSImpl <em>HXS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.HXSImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getHXS()
   * @generated
   */
  int HXS = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HXS__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>HXS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HXS_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.BEImpl <em>BE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.BEImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getBE()
   * @generated
   */
  int BE = 9;

  /**
   * The number of structural features of the '<em>BE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link a2b.a2B.impl.LEImpl <em>LE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see a2b.a2B.impl.LEImpl
   * @see a2b.a2B.impl.A2BPackageImpl#getLE()
   * @generated
   */
  int LE = 10;

  /**
   * The number of structural features of the '<em>LE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link a2b.a2B.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see a2b.a2B.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link a2b.a2B.Model#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see a2b.a2B.Model#getElement()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Element();

  /**
   * Returns the meta object for class '{@link a2b.a2B.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see a2b.a2B.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link a2b.a2B.DB <em>DB</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DB</em>'.
   * @see a2b.a2B.DB
   * @generated
   */
  EClass getDB();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.DB#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.DB#getValue()
   * @see #getDB()
   * @generated
   */
  EAttribute getDB_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.Base64 <em>Base64</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Base64</em>'.
   * @see a2b.a2B.Base64
   * @generated
   */
  EClass getBase64();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.Base64#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.Base64#getValue()
   * @see #getBase64()
   * @generated
   */
  EAttribute getBase64_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.ORG <em>ORG</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ORG</em>'.
   * @see a2b.a2B.ORG
   * @generated
   */
  EClass getORG();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.ORG#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.ORG#getValue()
   * @see #getORG()
   * @generated
   */
  EAttribute getORG_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.INCLUDE <em>INCLUDE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>INCLUDE</em>'.
   * @see a2b.a2B.INCLUDE
   * @generated
   */
  EClass getINCLUDE();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.INCLUDE#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.INCLUDE#getValue()
   * @see #getINCLUDE()
   * @generated
   */
  EAttribute getINCLUDE_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.MAC <em>MAC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MAC</em>'.
   * @see a2b.a2B.MAC
   * @generated
   */
  EClass getMAC();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.MAC#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.MAC#getValue()
   * @see #getMAC()
   * @generated
   */
  EAttribute getMAC_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.IP <em>IP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IP</em>'.
   * @see a2b.a2B.IP
   * @generated
   */
  EClass getIP();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.IP#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.IP#getValue()
   * @see #getIP()
   * @generated
   */
  EAttribute getIP_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.HXS <em>HXS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>HXS</em>'.
   * @see a2b.a2B.HXS
   * @generated
   */
  EClass getHXS();

  /**
   * Returns the meta object for the attribute '{@link a2b.a2B.HXS#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see a2b.a2B.HXS#getValue()
   * @see #getHXS()
   * @generated
   */
  EAttribute getHXS_Value();

  /**
   * Returns the meta object for class '{@link a2b.a2B.BE <em>BE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BE</em>'.
   * @see a2b.a2B.BE
   * @generated
   */
  EClass getBE();

  /**
   * Returns the meta object for class '{@link a2b.a2B.LE <em>LE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LE</em>'.
   * @see a2b.a2B.LE
   * @generated
   */
  EClass getLE();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  A2BFactory getA2BFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link a2b.a2B.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.ModelImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENT = eINSTANCE.getModel_Element();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.InstructionImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.DBImpl <em>DB</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.DBImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getDB()
     * @generated
     */
    EClass DB = eINSTANCE.getDB();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DB__VALUE = eINSTANCE.getDB_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.Base64Impl <em>Base64</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.Base64Impl
     * @see a2b.a2B.impl.A2BPackageImpl#getBase64()
     * @generated
     */
    EClass BASE64 = eINSTANCE.getBase64();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASE64__VALUE = eINSTANCE.getBase64_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.ORGImpl <em>ORG</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.ORGImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getORG()
     * @generated
     */
    EClass ORG = eINSTANCE.getORG();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORG__VALUE = eINSTANCE.getORG_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.INCLUDEImpl <em>INCLUDE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.INCLUDEImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getINCLUDE()
     * @generated
     */
    EClass INCLUDE = eINSTANCE.getINCLUDE();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INCLUDE__VALUE = eINSTANCE.getINCLUDE_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.MACImpl <em>MAC</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.MACImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getMAC()
     * @generated
     */
    EClass MAC = eINSTANCE.getMAC();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAC__VALUE = eINSTANCE.getMAC_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.IPImpl <em>IP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.IPImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getIP()
     * @generated
     */
    EClass IP = eINSTANCE.getIP();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IP__VALUE = eINSTANCE.getIP_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.HXSImpl <em>HXS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.HXSImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getHXS()
     * @generated
     */
    EClass HXS = eINSTANCE.getHXS();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HXS__VALUE = eINSTANCE.getHXS_Value();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.BEImpl <em>BE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.BEImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getBE()
     * @generated
     */
    EClass BE = eINSTANCE.getBE();

    /**
     * The meta object literal for the '{@link a2b.a2B.impl.LEImpl <em>LE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see a2b.a2B.impl.LEImpl
     * @see a2b.a2B.impl.A2BPackageImpl#getLE()
     * @generated
     */
    EClass LE = eINSTANCE.getLE();

  }

} //A2BPackage
