/**
 * generated by Xtext 2.17.0
 */
package a2b.a2B;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BE</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see a2b.a2B.A2BPackage#getBE()
 * @model
 * @generated
 */
public interface BE extends Instruction
{
} // BE
