/**
 * generated by Xtext 2.17.0
 */
package a2b.a2B;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LE</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see a2b.a2B.A2BPackage#getLE()
 * @model
 * @generated
 */
public interface LE extends Instruction
{
} // LE
