/*
 * generated by Xtext 2.17.0
 */
package a2b.ide

import a2b.A2BRuntimeModule
import a2b.A2BStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class A2BIdeSetup extends A2BStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new A2BRuntimeModule, new A2BIdeModule))
	}
	
}
