/*
 * generated by Xtext 2.17.0
 */
package a2b.parser.antlr;

import a2b.parser.antlr.internal.InternalA2BParser;
import a2b.services.A2BGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class A2BParser extends AbstractAntlrParser {

	@Inject
	private A2BGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalA2BParser createParser(XtextTokenStream stream) {
		return new InternalA2BParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public A2BGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(A2BGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
